Repository aimee-gm/react-gender-input, pull requests merged in 2018-11, with the labels that each got.

#12 Move gender value from internal component state to props
  demo/assets/components/demo-app.tsx
  demo/assets/components/gender-input-demo.tsx
  lib/gender-input.tsx
  package-lock.json
  package.json
  test/demo.code-block.spec.tsx
  test/demo.demo-app.spec.tsx
  test/demo.gender-input-demo.spec.tsx
  test/demo.param-toggle.spec.tsx
  test/gender-input.spec.tsx
Labels: enhancement

#13 Update readme to include value documentation
  README.md
  demo/assets/components/demo-app.tsx
Labels: documentation

#16 Deploy condition
  .travis.yml
Labels: enhancement

#17 Switch to gender-options dependency
  lib/gender-input.tsx
  lib/genders.ts
  package-lock.json
  package.json
Labels: enhancement

#19 Avoid building the demo app twice in the same CI job
  package.json
Labels: bug
